---
server_path: /home/server
server_public_dir: web
server_timezone: Europe/Berlin

project_name: dev.local

user: ubuntu
# Password: vagrant
user_password: "$6$hWE5LONZw3V8gG$/1pzSCh0m7njjrmrFm5S6sCp6I//Hy3MOuvuo39aC7YU3xi1hULiSGax/3eBqZ9nO6dTqxGRU.lhqg/oFKh/x0"
# To generate a new password for the user run this command
# mkpasswd password_here --method=sha-512

env_type: dev

webserver_name: nginx # apache2, nginx, none

nginx_port: 80
apache2_port: 80

php_xdebug_enabled: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_autostart: 1
php_xdebug_profiler_enable: 1
php_xdebug_remote_connect_back: 1

mysql_db_user: developer
mysql_db_pass: develop123
mysql_db_name: development

## NodeJS
## Pin-Priority of NodeSource repository
nodejs_nodesource_pin_priority: 500
nodejs_version: "6.x"


java_home: ""
# Set java_packages if you would like to use a different version than the default (OpenJDK 1.7).
# JDK version options include:
#   - java
#   - openjdk-8-jdk
#   - openjdk-9-jdk
java_packages:
  - openjdk-8-jdk

elasticsearch_network_host: 0.0.0.0
elasticsearch_http_port: 9200
elasticsearch_script_inline: true
elasticsearch_script_indexed: true
