---
- hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - environment.yml

  pre_tasks:
    - name: "update apt cache"
      apt: update_cache=yes

  roles:
    - { role: common }
    - { role: git }
    - { role: banner }
    - { role: ntp-timezone }
    - { role: ssh }
    - { role: oh-my-zsh }
    - { role: nodejs }
    - { role: "server-{{ webserver_name }}", when: webserver_name != 'none' }
    - { role: php }
    - { role: kisphp }
    #- { role: redis }
    - { role: mysql }
    - { role: project }
    #- { role: jekyll }
    #- { role: fail2ban }
