---
- hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - config.yml

  pre_tasks:
    - name: "update apt cache"
      apt: update_cache=yes

  roles:
    - { role: common }
    - { role: git }
    - { role: banner }
    - { role: ntp-timezone }
    - { role: ssh }
    - { role: crons }
    - { role: oh-my-zsh }
    - { role: "server-{{ webserver_name }}", when: webserver_name != 'none' }
    - { role: php }
    - { role: composer }
    - { role: nodejs }
    - { role: kisphp }
    - { role: mysql }
    - { role: project }
#    - { role: redis }
#    - { role: jekyll }
#    - { role: fail2ban }

    # Java and elasticsearch are disabled by default, if you need them, just uncomment the following lines
#    - { role: java }
#    - { role: elasticsearch }
#    - { role: kibana }
#    - { role: jenkins }
