php7_fpm_service_name: "php{{ php7_version }}-fpm"

php_ppa: "ppa:ondrej/php"

php_apt_modules:
  - php{{ php7_version }}-common
  - php{{ php7_version }}-cli
  - php{{ php7_version }}-intl
  - php{{ php7_version }}-curl
  - php{{ php7_version }}-cgi
  - php{{ php7_version }}-fpm
  - php{{ php7_version }}-mysql
  - php{{ php7_version }}-gd
  - php{{ php7_version }}-xml
  - php{{ php7_version }}-mbstring
  - php{{ php7_version }}-zip
  - php-imagick
  - php-xdebug

php_ini:
  fpm:
    short_open_tag: Off
    max_execution_time: 30
    max_input_time: 30
    memory_limit: 512M
    display_errors: Off
    post_max_size: 8M
    upload_max_filesize: 100M
    max_file_uploads: 10
    allow_url_fopen: Off
    allow_url_include: Off
  cli:
    short_open_tag: Off
    max_execution_time: 30
    max_input_time: 30
    memory_limit: -1
    display_errors: On
    post_max_size: 8M
    upload_max_filesize: 20M
    max_file_uploads: 10
    allow_url_fopen: On
    allow_url_include: Off
