- name: "Install python apt modules"
  apt:
    name: "{{ python_apt_modules }}"
    update_cache: yes
  tags:
    - python

- name: "Download pip installer"
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: 0644
  tags:
    - python

- name: "Install Python PIP"
  command: python /tmp/get-pip.py
  tags:
    - python

- name: "Delete pip installer"
  file:
    path: /tmp/get-pip.py
    state: absent
  tags:
    - python

- name: "Install Python PIP modules"
  pip:
    name: "{{ python_pip_modules }}"
  ignore_errors: yes
  tags:
    - python
