---
- name: "Ensure dependency is installed"
  apt: name=apt-transport-https state=present

- name: Add Kibana repository.
  apt_repository:
    repo: 'deb https://packages.elastic.co/kibana/{{ kibana_version }}/debian stable main'
    state: present
    update_cache: yes

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/opt/kibana/config/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
