---
- name: "Add repository for Ubuntu"
  become: true
  apt_repository:
    repo: "{{ php_ppa }}"
  tags:
    - php

- name: "Install PHP 7 packages"
  apt:
    name: "{{ php_apt_modules }}"
    update_cache: yes
    state: latest
  tags:
    - php

- name: "Generate PHP FPM pool.d config"
  template:
    src: "php7/fpm/pool.d/www.conf.j2"
    dest: "/etc/php/{{ php7_version }}/fpm/pool.d/www.conf"
    owner: "root"
    group: "root"
    mode: 0644
  tags:
    - php

- name: "Generate FPM PHP ini"
  template:
    src: "php7/php.ini.j2"
    dest: "/etc/php/{{ php7_version }}/fpm/php.ini"
    owner: "root"
    group: "root"
    mode: 0644
  vars:
    config: "{{ php_ini.fpm }}"
  tags:
    - php

- name: "Generate CLI PHP ini"
  template:
    src: "php7/php.ini.j2"
    dest: "/etc/php/{{ php7_version }}/cli/php.ini"
    owner: "root"
    group: "root"
    mode: 0644
  vars:
    config: "{{ php_ini.cli }}"
  tags:
    - php

- name: "Make sure the socket file has the correct rights"
  file:
    path: "/var/run/php/php{{ php7_version }}-fpm.sock"
    owner: "root"
    group: "root"
    mode: "o+rw"
    force: "yes"
  become: yes
  become_method: "sudo"
  when: webserver_name == "nginx"
  tags:
    - php

- name: "Disable PHP Opcache"
  file:
    path: "/etc/php/7.1/{{ item }}/conf.d/10-opcache.ini"
    state: absent
  ignore_errors: True
  with_items:
    - cli
    - fpm
  tags:
    - php

- name: "Restart php-fpm"
  service:
    name: "{{ php7_fpm_service_name }}"
    state: restarted
  become: yes
  become_method: "sudo"
  when: webserver_name == "nginx"
  tags:
    - php

- name: "Install apache packages for php 7"
  apt:
    name: libapache2-mod-php7.1
    update_cache: yes
    state: present
  when: webserver_name == "apache2"
  tags:
    - php
