---
#- name: "Add debian dotdeb packages"
#  apt_repository:
#    repo: deb http://packages.dotdeb.org jessie all
#    state: present

#- name: "Add debian dotdeb src packages"
#  apt_repository:
#    repo: deb-src http://packages.dotdeb.org jessie all
#    state: present

#- name: "Add apt key for Debian"
#  apt_key:
#    url: https://www.dotdeb.org/dotdeb.gpg
#    state: present

#- name: "Update apt"
#  apt:
#    update_cache: yes

- name: "Install PHP 7 packages"
  apt: name={{ item }} update_cache=yes state=latest
  with_items: "{{ php_apt_modules }}"

- name: "Generate PHP FPM pool.d config"
  template:
    src: "pool.d/www.conf.j2"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    owner: "root"
    group: "root"
    mode: 0644
    force: yes

- name: "Generate FPM PHP ini"
  template:
    src: "php.ini.j2"
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    owner: "root"
    group: "root"
    mode: 0644
    force: yes

- name: "Generate CLI PHP ini"
  template:
    src: "php.ini.j2"
    dest: "/etc/php/{{ php_version }}/cli/php.ini"
    owner: "root"
    group: "root"
    mode: 0644
    force: yes

- name: "Make sure the socket file has the correct rights"
  file:
    path: "/var/run/php/php{{ php_version }}-fpm.sock"
    owner: "root"
    group: "root"
    mode: "o+rw"
    force: "yes"
  become: yes
  become_method: "sudo"
  when: webserver_name == "nginx"

- name: "Restart php-fpm"
  service: name={{ php7_fpm_service_name }} state=restarted
  become: yes
  become_method: "sudo"
  when: webserver_name == "nginx"
