---
- name: "Add repository for Ubuntu"
  become: true
  apt_repository: repo={{ php_ppa }}

- name: "Install PHP 7 packages"
  apt: name={{ item }} update_cache=yes state=latest
  with_items: "{{ php_apt_modules }}"

- name: "Generate PHP FPM pool.d config"
  template:
    src: "php7/fpm/pool.d/www.conf.j2"
    dest: "/etc/php/{{ php7_version }}/fpm/pool.d/www.conf"
    owner: "root"
    group: "root"
    mode: 0644

- name: "Generate FPM PHP ini"
  template:
    src: "php7/php.ini.j2"
    dest: "/etc/php/{{ php7_version }}/fpm/php.ini"
    owner: "root"
    group: "root"
    mode: 0644
  vars:
    config: "{{ php_ini.fpm }}"

- name: "Generate CLI PHP ini"
  template:
    src: "php7/php.ini.j2"
    dest: "/etc/php/{{ php7_version }}/cli/php.ini"
    owner: "root"
    group: "root"
    mode: 0644
  vars:
    config: "{{ php_ini.cli }}"

- name: "Make sure the socket file has the correct rights"
  file:
    path: "/var/run/php/php{{ php7_version }}-fpm.sock"
    owner: "root"
    group: "root"
    mode: "o+rw"
    force: "yes"
  become: yes
  become_method: "sudo"
  when: webserver_name == "nginx"

- name: "Restart php-fpm"
  service: name={{ php7_fpm_service_name }} state=restarted
  become: yes
  become_method: "sudo"
  when: webserver_name == "nginx"
