---
- name: "Generate xdebug.ini"
  template:
    src: xdebug.ini.j2
    dest: "/etc/php/{{ php7_version }}/mods-available/xdebug.ini"
    owner: "root"
    group: "root"
    mode: 0644
  when: php_xdebug_enabled == True
  tags:
    - php
    - xdebug

- name: "Enable Apache XDEBUG"
  file:
    src="/etc/php/{{ php7_version }}/mods-available/xdebug.ini"
    dest="/etc/php/{{ php7_version }}/apache2/conf.d/20-xdebug.ini"
    owner=root
    group=root
    state=link
  when: php_xdebug_enabled == True and webserver_name == 'apache2'
  ignore_errors: True
  tags:
    - php
    - xdebug

- name: "Enable CLI XDEBUG"
  file:
    src="/etc/php/{{ php7_version }}/mods-available/xdebug.ini"
    dest="/etc/php/{{ php7_version }}/cli/conf.d/20-xdebug.ini"
    owner=root
    group=root
    state=link
  when: php_xdebug_enabled == True
  ignore_errors: True
  tags:
    - php
    - xdebug

- name: "Enable FPM XDEBUG"
  file:
    src="/etc/php/{{ php7_version }}/mods-available/xdebug.ini"
    dest="/etc/php/{{ php7_version }}/fpm/conf.d/20-xdebug.ini"
    owner=root
    group=root
    state=link
  when: php_xdebug_enabled == True
  ignore_errors: True
  tags:
    - php
    - xdebug

- name: "Disable Apache Xdebug"
  file: path="/etc/php/{{ php7_version }}/apache2/conf.d/20-xdebug.ini" state=absent
  when: php_xdebug_enabled != True
  ignore_errors: True
  tags:
    - php
    - xdebug

- name: "Disable CLI Xdebug"
  file: path="/etc/php/{{ php7_version }}/cli/conf.d/20-xdebug.ini" state=absent
  when: php_xdebug_enabled != True
  ignore_errors: True
  tags:
    - php
    - xdebug

- name: "Disable FPM Xdebug"
  file: path="/etc/php/{{ php7_version }}/fpm/conf.d/20-xdebug.ini" state=absent
  when: php_xdebug_enabled != True
  ignore_errors: True
  tags:
    - php
    - xdebug
