---
- name: "Install git"
  apt:
    name: ['git', 'git-core']
    update_cache: yes
  tags:
    - git

- name: "Make sure git config file exists"
  file:
    path: /home/{{ user }}/.gitconfig
    state: touch
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - git

- name: "Git config push simple"
  git_config:
    name: push.default
    value: simple
    scope: global
  become_user: "{{ user }}"
  tags:
    - git


#- name: "Configure git email"
#  git_config:
#    name: user.email
#    scope: global
#    value: "{{ git_email }}"
#  become_user: "{{ user }}"

#- name: "Configure git username"
#  git_config:
#    name: user.name
#    scope: global
#    value: "{{ git_username }}"
#  become_user: "{{ user }}"

- name: "Set core editor to vim"
  git_config:
    name: core.editor
    scope: global
    value: vim
  become_user: "{{ user }}"
  tags:
    - git

- name: "Set color"
  git_config:
    name: color.ui
    scope: global
    value: true
  become_user: "{{ user }}"
  tags:
    - git

- name: "When pulling code, always rebase your local changes. (note that you probably want to set this to false (or just fetch+merge instead of pull) when working on a shared remote branch (trains are fine). See https://git-scm.com/book/en/v2/Git-Branching-Rebasing)"
  git_config:
    name: pull.rebase
    scope: global
    value: true
  become_user: "{{ user }}"
  tags:
    - git

- name: "When pushing code, always push only your current branch to a branch of the same name"
  git_config:
    name: push.default
    scope: global
    value: current
  become_user: "{{ user }}"
  tags:
    - git

- name: "Automatically prune deleted branches from your local copy when you fetch (or pull)"
  git_config:
    name: fetch.prune
    scope: global
    value: true
  become_user: "{{ user }}"
  tags:
    - git

- name: "Tell git not to mess with your line endings"
  git_config:
    name: core.autocrlf
    scope: global
    value: false
  become_user: "{{ user }}"
  tags:
    - git

- name: "Show branch names with git log"
  git_config:
    name: log.decorate
    scope: global
    value: short
  become_user: "{{ user }}"
  tags:
    - git

- name: "Enable parallel index preload for operations like git diff"
  git_config:
    name: core.preloadindex
    scope: global
    value: true
  become_user: "{{ user }}"
  tags:
    - git

- name: "Git for Windows offers a filesystem cache which accelerates operations in many cases, after an initial 'warm-up'"
  git_config:
    name: core.fscache
    scope: global
    value: true
  become_user: "{{ user }}"
  tags:
    - git

- name: "Ignore symlinks"
  git_config:
    name: core.symlinks
    scope: global
    value: false
  become_user: "{{ user }}"
  tags:
    - git

- name: "Disable SSL verify"
  git_config:
    name: http.sslVerify
    scope: global
    value: false
  become_user: "{{ user }}"
  tags:
    - git
