---
- name: "Kisphp Dotfiles"
  get_url:
    url: https://gitlab.com/marius-rizac/dotfiles/raw/master/install.sh
    dest: /tmp/kisphp-install.sh
    mode: 0755
  tags:
    - kisphp

- name: "Install Kisphp Dotfiles"
  shell: /tmp/kisphp-install.sh
  become: true
  become_user: "{{ user }}"
  args:
    chdir: /home/{{ user }}
    executable: /bin/bash
  tags:
    - kisphp

- name: "Remove kisphp-install script"
  file: path=/tmp/kisphp-install.sh state=absent
  tags:
    - kisphp
