---
- name: "Clone server_manager repository"
  git:
    repo: "{{ server_manager.repo }}"
    dest: "{{ server_manager.path }}"
    clone: yes
    update: no
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"
  ignore_errors: True
  tags:
    - server-manager
    - kisphp

- name: "Run composer install for server-manager"
  composer:
    command: "install"
    prefer_dist: "yes"
    arguments: -n -o -a
    working_dir: "{{ server_manager.path }}"
  become: yes
  become_user: "{{ user }}"
  ignore_errors: True
  tags:
    - server-manager
    - kisphp
