---
- name: reload apache
  service: name=apache2 state=reloaded

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload php7-fpm
  service: name=php{{ php7_version }}-fpm state=reloaded
