---
- name: "Install Jekill"
  apt:
    name: jekyll
    state: present

- name: "Build site docs"
  command: /usr/bin/jekyll build
  args:
    chdir: "{{ server_path }}"
    creates: "{{ server_path }}/_site/"
  tags:
    - jekyll
